services:
  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: mythweaver-backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
      - DATABASE_URL=sqlite:///./data/app.db
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - SENTRY_DSN=${SENTRY_DSN:-}
    volumes:
      - backend_data:/app/data
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - mythweaver-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mythweaver-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=/api/v1
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - mythweaver-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: mythweaver-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - mythweaver-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx reverse proxy (production)
  nginx:
    image: nginx:alpine
    container_name: mythweaver-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - mythweaver-network
    profiles:
      - production

volumes:
  backend_data:
    driver: local
  redis_data:
    driver: local
  nginx_logs:
    driver: local

networks:
  mythweaver-network:
    driver: bridge


